import type { DraftPayload } from "@/shared/contracts";

/**
 * Turns a reviewed draft into portable text a seller can paste anywhere —
 * Facebook Marketplace, Craigslist, Mercari, Poshmark, Depop, a Note, an email.
 *
 * This is deliberately marketplace-agnostic. eBay-specific artifacts (category
 * IDs, item specifics keyed to eBay's taxonomy, publish blockers) are either
 * omitted or relabelled in plain language, because the value here is for
 * sellers who are *not* publishing to eBay.
 */

function formatPrice(value: number) {
  return `$${value.toFixed(2)}`;
}

/** The price the seller actually settled on, not the AI's first suggestion. */
function resolvePrice(draft: DraftPayload) {
  if (draft.manualPriceOverride) {
    return { price: draft.manualPriceOverride.price, strategy: draft.manualPriceOverride.strategy, isOverride: true };
  }
  const recommended = draft.pricing.options.find((option) => option.strategy === draft.pricing.recommendedStrategy)
    ?? draft.pricing.options[0];
  if (!recommended) return null;
  return { price: recommended.price, strategy: recommended.strategy, isOverride: false };
}

export type ListingExportFormat = "markdown" | "plain";

export function buildListingExport(draft: DraftPayload, format: ListingExportFormat = "markdown"): string {
  const md = format === "markdown";
  const h1 = (text: string) => (md ? `# ${text}` : text.toUpperCase());
  const h2 = (text: string) => (md ? `## ${text}` : `\n${text.toUpperCase()}`);
  const bullet = (text: string) => (md ? `- ${text}` : `• ${text}`);
  const lines: string[] = [];

  lines.push(h1(draft.selectedTitle), "");

  const resolved = resolvePrice(draft);
  if (resolved) {
    lines.push(md ? `**${formatPrice(resolved.price)}**` : formatPrice(resolved.price));
    lines.push("");
  }

  lines.push(h2("Condition"));
  lines.push(draft.condition);
  if (draft.conditionNotes.trim()) lines.push(draft.conditionNotes.trim());
  lines.push("");

  if (draft.description.trim()) {
    lines.push(h2("Description"));
    lines.push(draft.description.trim());
    lines.push("");
  }

  // Item specifics read as plain "Brand: Nike" detail lines off eBay.
  if (draft.itemSpecifics.length > 0) {
    lines.push(h2("Details"));
    for (const specific of draft.itemSpecifics) {
      if (!specific.name.trim() || !specific.value.trim()) continue;
      lines.push(bullet(`${specific.name}: ${specific.value}`));
    }
    lines.push("");
  }

  if (draft.categoryGuess.categoryName.trim()) {
    lines.push(h2("Category"));
    lines.push(draft.categoryGuess.categoryPath ?? draft.categoryGuess.categoryName);
    lines.push("");
  }

  // Pricing context is the part sellers cannot easily reproduce themselves, so
  // it travels with the listing even though no marketplace field maps to it.
  if (draft.pricing.sampleSize > 0) {
    lines.push(h2("Pricing research"));
    lines.push(bullet(
      `Comparable active listings ranged ${formatPrice(draft.pricing.rangeLow)}–${formatPrice(draft.pricing.rangeHigh)}, `
        + `median ${formatPrice(draft.pricing.rangeMedian)} (${draft.pricing.sampleSize} listings).`,
    ));
    if (resolved?.isOverride) {
      lines.push(bullet(`You set this price manually at ${formatPrice(resolved.price)}.`));
    }
    lines.push(bullet("These are asking prices from active listings, not confirmed sale prices."));
    lines.push("");
  }

  if (draft.missingInfo.length > 0) {
    lines.push(h2("Worth adding before you post"));
    for (const item of draft.missingInfo) lines.push(bullet(item));
    lines.push("");
  }

  lines.push(md ? "---" : "");
  lines.push("Generated by ListingOS.");

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

/** Short, for a share-sheet subject line or an email header. */
export function buildListingExportSubject(draft: DraftPayload): string {
  const resolved = resolvePrice(draft);
  return resolved ? `${draft.selectedTitle} — ${formatPrice(resolved.price)}` : draft.selectedTitle;
}
